# FriendlyChat Codelab

use_frameworks!
platform :ios, '7.0'

pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Crash'
pod 'Firebase/Database'
pod 'Firebase/RemoteConfig'

target 'OrderApp' do
end
